server:
  port: 8084
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://172.20.49.84:3306/hmily_account?useUnicode=true&characterEncoding=utf8
        username: zero
        password: zero

mybatis:
  type-aliases-package: org.dromara.hmily.demo.common.account.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
    path: "./logs"

